services:
  db:
    image: postgres:16
    restart: always
    container_name: sps_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sps_network

volumes:
  postgres_data:

networks:
  sps_network:
