services:
  - type: web
    name: sps-service  # Your service name
    env: go
    region: oregon  # or choose your preferred region
    buildCommand: go build -o main
    startCommand: ./main
    envVars:
      # Database configuration
      - key: DB_HOST
        value: 10.14.237.200
      - key: DB_PORT
        value: "5435"  # Note: string value
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false  # Mark as non-sync for secrets
      - key: DB_NAME
        value: sps_service
      - key: DB_SSL_MODE
        value: disable
        
      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true  # Let Render generate a secure one
        sync: false
        
      # Server Configuration
      - key: SERVER_PORT
        value: "8090"
        
      # CORS Configuration
      - key: CORS
        value: "http://localhost:5173, https://smart-parking-solution.vercel.app/"
        
      # Client Credentials
      - key: CLIENT_KEY
        value: 0cb92c12-4287-4255-b9a9-274bacd65668
        sync: false
      - key: CLIENT_SECRET_KEY
        value: 5dcd3db9-97fb-49f9-ab3b-ed31a50ed2c3
        sync: false
        
      # Proxy Configuration
      - key: PROXY_URL
        value: http://10.90.2.105:3128
        
      # API Configuration
      - key: SPS_BASE_API
        value: https://devintegrationv2.skyparking.online
    
    # Health check configuration
    healthCheckPath: /health
    # Uncomment if you need custom port for health checks
    # healthCheckPath: :8090/health
    
    # Scaling configuration (optional)
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70